#############################################################################
# Makefile for building: GraphBuilder
# Generated by qmake (3.1) (Qt 6.5.0)
# Project:  GraphBuilder.pro
# Template: vcapp
# Command: D:\Softwares\Qt6.5\6.5.0\mingw_64\bin\qmake.exe -o Makefile GraphBuilder.pro -tp vc
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\Softwares\Qt6.5\6.5.0\mingw_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Softwares\Qt6.5\6.5.0\mingw_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Softwares\Qt6.5\6.5.0\mingw_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = GraphBuilder_resource_res.o
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: GraphBuilder.pro ../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/win32-g++/qmake.conf ../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/spec_pre.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/device_config.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/sanitize.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/gcc-base.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/g++-base.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/windows-vulkan.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/g++-win32.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/windows-desktop.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/qconfig.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_core.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_help.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_network.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_png_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qt_functions.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qt_config.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/win32-g++/qmake.conf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/spec_post.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/exclusive_builds.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/toolchain.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/default_pre.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/default_pre.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/resolve_config.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/exclusive_builds_post.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/default_post.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/entrypoint.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/precompile_header.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/warn_on.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qt.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/resources_functions.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/resources.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/moc.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/opengl.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/uic.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qmake_use.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/file_copies.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/windows.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/testcase_targets.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/exceptions.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/yacc.prf \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/lex.prf \
		GraphBuilder.pro \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Svg.prl \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Widgets.prl \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Gui.prl \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Core.prl \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6EntryPoint.prl \
		.qmake.stash \
		../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/build_pass.prf \
		icons.qrc
	$(QMAKE) -o Makefile GraphBuilder.pro -tp vc
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/spec_pre.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/device_config.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/sanitize.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/gcc-base.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/g++-base.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/windows-vulkan.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/g++-win32.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/common/windows-desktop.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/qconfig.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_ext_freetype.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_ext_libpng.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_core.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_designer.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_gui.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_help.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssettings.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_linguist.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_network.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_png_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qml.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quick.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_sql.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svg.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_xml.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qt_functions.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qt_config.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/win32-g++/qmake.conf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/spec_post.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/exclusive_builds.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/toolchain.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/default_pre.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/default_pre.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/resolve_config.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/exclusive_builds_post.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/default_post.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/entrypoint.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/precompile_header.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/warn_on.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qt.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/resources_functions.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/resources.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/moc.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/opengl.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/uic.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/qmake_use.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/file_copies.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/win32/windows.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/testcase_targets.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/exceptions.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/yacc.prf:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/lex.prf:
GraphBuilder.pro:
../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Svg.prl:
../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Widgets.prl:
../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Gui.prl:
../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6Core.prl:
../../../Softwares/Qt6.5/6.5.0/mingw_64/lib/Qt6EntryPoint.prl:
.qmake.stash:
../../../Softwares/Qt6.5/6.5.0/mingw_64/mkspecs/features/build_pass.prf:
icons.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile GraphBuilder.pro -tp vc

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
